apiVersion: v1
kind: Service
metadata:
  name: kong-dp-metrics
  namespace: kong
spec:
  ports:
  - name: kong-metrics
    port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: kong-dp
    app.kubernetes.io/name: kong
  sessionAffinity: None
  type: NodePort