ingressController:
 enabled: true
  
image:
 repository: kong/kong-gateway
 tag: "3.8.0.0"
  
env:
 admin_gui_url: https://kong-manager93.lab8088.online
 admin_gui_api_url: https://kong-admin93.lab8088.online
 #Change the secret and set cookie_secure to true if using a HTTPS endpoint
 admin_gui_session_conf: '{"secret":"secret","storage":"kong","cookie_secure":true}'
 
  
 # Database
 database: postgres
 pg_database: kong
 pg_user: kong
 pg_password: demo123
 pg_host: kong-cp-postgresql.kong.svc.cluster.local
 pg_ssl: "on"
  
# Enterprise functionality
enterprise:
 enabled: true
 license_secret: kong-enterprise-license
 rbac:
   enabled: true
   admin_gui_auth: basic-auth
  
admin:
 enabled: true
 http:
   enabled: true
 tls:
   enabled: true
  
cluster:
 enabled: true
 tls:
   enabled: true
  
clustertelemetry:
 enabled: true
 tls:
   enabled: true
  
manager:
 enabled: true
 http:
   enabled: true
 tls:
   enabled: true
  
proxy:
  annotations:
    prometheus.io/port: "9542"
    prometheus.io/scrape: "true"
  enabled: true

status:
  enabled: true

postgresql:
  enabled: true
  auth:
    password: demo123
    
serviceMonitor:
  enabled: true
