ingressController:
 enabled: false
 env:
   publish_service: kong/kong-dp-kong-proxy
   kong_admin_token: kong_admin_password
  
image:
 repository: kong/kong-gateway
 tag: "3.8.1.0"

secretVolumes:
 - kong-cluster-cert

env:
 admin_gui_url: https://kong-manager93.lab8088.online
 admin_gui_api_url: https://kong-admin93.lab8088.online
 #Change the secret and set cookie_secure to true if using a HTTPS endpoint
 admin_gui_session_conf: '{"secret":"secret","storage":"kong","cookie_secure":true}'

 # This is a control_plane node
 role: control_plane
 # These certificates are used for control plane / data plane communication
 cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
 cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key 
  
 # Database
 database: postgres
 pg_database: kong
 pg_user: kong
 pg_password: demo123
 pg_host: kong-cp-postgresql.kong.svc.cluster.local
 pg_ssl: "on"
  
 # Kong Manager password
 password: kong_admin_password
 
# Enterprise functionality
enterprise:
 enabled: true
 license_secret: kong-enterprise-license
 rbac:
   enabled: true
   admin_gui_auth: basic-auth
  
admin:
 enabled: true
 http:
   enabled: true
 tls:
   enabled: true
  
cluster:
 enabled: true
 tls:
   enabled: true
  
clustertelemetry:
 enabled: true
 tls:
   enabled: true
  
manager:
 enabled: true
 http:
   enabled: true
 tls:
   enabled: true
  
proxy:
  annotations:
    prometheus.io/port: "9542"
    prometheus.io/scrape: "true"
  enabled: true

status:
  enabled: true

postgresql:
  enabled: true
  auth:
    password: demo123
    
serviceMonitor:
  enabled: true
